### ISSUE TITLE
Request User delete endpoint  not working

### ISSUE THREAD

**Issue by sruthisanthoshmuth** [rollbar/api-examples#4]
The request User delete API respond with 404 user Person Not Found, even when the user exist.

**Comment by adithyamenon** [comment]
I am facing the same issue as well. [This](https://explorer.docs.rollbar.com/#operation/delete-a-person) is the REST API documentation which I followed. I get a JSON response as follows:
`{
  "err": 1,
  "message": "Invalid or missing person id, username, or email."
}`

Is this what you were facing? @sruthisanthoshmuth

**Comment by sergii-holota** [comment]
I have the same issue. I am using url like 
`https://api.rollbar.com/api/1/people/delete_jobs/?id=<id_here>`
and I am getting an error
`
{
  "err": 1,
  "message": "Person Not Found"
}
`

**Comment by bxsx** [comment]
@sruthisanthoshmuth @adithyamenon @sergii-holota 

Thanks for reporting and sorry for the confusion.

The [endpoint](https://explorer.docs.rollbar.com/#operation/delete-a-person) provides support for [People Tracking](https://docs.rollbar.com/docs/person-tracking)
You can look up valid values at: https://rollbar.com/{account_name}/all/people/

If the problem persists I recommend contacting us directly at support@rollbar.com so we can investigate each issue in detail.

**Comment by bxsx** [comment]
Optimistically, closing it as resolved. Please let us know if this should be reopened.
Thanks
